name: Pull Request Checks

on:
  pull_request:
    branches:
      - main

jobs:
  sast_scan:
    name: Static Application Security Testing (SAST)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run SAST with Bandit
        run: |
          pip install bandit
          bandit -r . || exit 1

  dependency_check:
    name: Dependency Vulnerabilities Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Dependency Check with Safety
        run: |
          pip install safety
          safety check || exit 1

  secrets_check:
    name: Secrets Detection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Secrets Detection with TruffleHog
        run: |
          pip install truffleHog
          trufflehog filesystem --directory . || exit 1
